# Generated by Django 4.2.3 on 2023-07-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField(max_length=50)),
                ('category_description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ItemForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField(max_length=100)),
                ('item_description', models.TextField(max_length=1000)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_categories', models.ManyToManyField(to='items.category')),
            ],
        ),
    ]
