# Generated by Django 4.2.3 on 2023-07-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='itemforsale',
            options={'verbose_name': 'Item for sale', 'verbose_name_plural': 'Items for sale'},
        ),
        migrations.AddField(
            model_name='itemforsale',
            name='item_image_url',
            field=models.URLField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
