# Generated by Django 4.2.3 on 2023-07-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_itemforsale_item_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemforsale',
            name='item_uuid',
            field=models.TextField(max_length=30, unique=True),
        ),
    ]
