# Generated by Django 4.2.3 on 2023-07-26 15:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_itemforsale_item_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemforsale',
            name='item_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
