# Generated by Django 4.2.3 on 2023-07-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_itemforsale_item_uuid'),
    ]

    operations = [
    ]
